target-version = "py311"

[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = [
    "A", "ANN", "ARG", "ASYNC", "B", "BLE", "C4", "DTZ", "E", "F", "FA", "FLY", "FURB",
    "G", "I", "ICN", "INT", "ISC", "LOG", "PERF", "PIE", "PL", "PTH", "Q",
    "RET", "RSE", "RUF", "SIM", "SLF", "SLOT", "T10", "TC", "TID", "TRY", "UP", "W", "YTT"
]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501", "TRY003", "ASYNC230"]
